### PR TITLE
Upgrade CI distribute step to use go 1.12

### LINKED ISSUE #72: Helper render issue causes failure
Given the following `_helper.tpl`:

```golang
{{- define "ingressClass" -}}
  {{- $ingressClass := .Values.ingress.class -}}
  {{- if .Values.global -}}
    {{- if .Values.global.ingressClass -}}
      {{- $ingressClass = .Values.global.ingressClass -}}
    {{- end -}}
  {{- end -}}
  {{- printf "%s" $ingressClass -}}
{{- end -}}
```

I actually ran into this issue with helm `2.11` and it was fixed somewhere in `2.12` but not explicitly. My _guess_ is this: https://github.com/helm/helm/pull/5300

In any case, here's what that looks like inside `ingress.yaml`:
```yaml
kubernetes.io/ingress.class: {{ template "ingressClass" . }}
```

And here's the failure on `helm unittest $CHARTNAME`:

```shell

### Chart [ mychart ] ./charts/mychart

 FAIL  test ingress     charts/mychart/tests/ingress_test.yaml
        - should set ingress class to nginx by default
                Error: parse error in "mychart/templates/_helper.tpl": template: collections/templates/_helper.tpl:49: unexpected "=" in operand


Charts:      1 failed, 0 passed, 1 total
Test Suites: 1 failed, 0 passed, 1 total
Tests:       1 failed, 1 errored, 0 passed, 1 total
Snapshot:    0 passed, 0 total
Time:        26.892096ms

Error: plugin "unittest" exited with error
```

The implication is there's a scope issue where the `=` inside the nested if doesn't have access to the variable defined in the second line of the helper above. It's imperative that the `=` work without it being changed to `:=` because that would actually assign a _new_ variable, that wouldn't be available outside the if, and thus couldn't be printed on the second to last line.

tl;dr; I'm wondering if upgrading `sprig` might fix this, but otherwise there's something else at play and helm fixed it (though perhaps unintentionally, haha).

### PR DESCRIPTION
**Pull request by dotLou**
Fixes #72 in latest binary

### CODE REVIEW

**Comment by dotLou** [comment]
@lrills - this should _actually_ fix it.

**Comment by dotLou** [comment]
@lrills - any chance this can get in? As it stands, the binary that's built isn't functional for me and I would love to be able to use this as part of my CI.

Alternatively, I'll fork this and produce a binary myself in the meantime.

**Comment by dotLou** [comment]
I went ahead, a while ago, and created a release on my fork that produces proper go 1.12 binaries so I can use that for some CI jobs on my end where I was running into the #72 issue. For anyone who runs into this, https://github.com/dotLou/helm-unittest/releases/tag/v0.1.5-patch-1

**Comment by dotLou** [comment]
@lrills Any chance this can be merged? I'd love to get rid of my fork if possible 🙏

**Comment by dotLou** [comment]
Bump! 🙏

**Comment by kir4h** [comment]
Why was the PR closed? (I guess maybe tired of waiting). I am actually running into the same issue, I will try your fork @dotLou, but I would prefer having this merged into this repository. (or to a different one if the maintainer wants to transfer its ownership)

**Comment by dotLou** [comment]
I've moved on and no longer need this for my work. My fork I'd still available (albeit in an archived state) though should you need it. This should indeed still be the fix you need

**Comment by kir4h** [comment]
Thanks for the clarification. For anyone ended up in this scenario, there is also an open PR from @quintush that addresses this and bumps used versions amongs other features, so meanwhile his fork can also be used for installation (`helm plugin install --debug https://github.com/quintush/helm-unittest/`)

**Pull request closed without merging**
