### PR TITLE
Updated sprig to v2.15.0 and helm to v2.9.1

### PR DESCRIPTION
**Pull request by kenji-fukasawa**
Hello,

I need to use the `ternary` function from [http://masterminds.github.io/sprig/defaults.html](sprig) in my charts.  The current dependency versions used by `helm-unittest` do not include that function and therefore throw `function "ternary" not defined` errors during testing.  I have updated the necessary dependencies to include the newer functionality.

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@lrills bump.
could maybe even jump to 2.10.0?
hoping it might fix https://github.com/lrills/helm-unittest/issues/53

**Comment by davidkarlsen** [comment]
Is this project abandonware?

**Comment by TD-4242** [comment]
I really hope not, it's a great resource.

**Comment by tahmmee** [comment]
hello

**Comment by walkafwalka** [comment]
Hey @kenji-fukasawa, @davidkarlsen, @TD-4242, and @tahmmee. I am trying to revive this project since the maintainer seems to be gone. I also tried contacting him separately, but no response. If he comes back, I plan to submit any changes I make on my back to this one.

For this particular request, I updated all of the dependencies with this MR [here](https://gitlab.com/walkafwalka/helm-unittest/merge_requests/3) and release of [0.2.0](https://gitlab.com/walkafwalka/helm-unittest/releases).

**Comment by TD-4242** [comment]
@walkafwalka Thank you for doing this.  When installing it got an error about a zip format, I downloaed your 2.1 release and copied the binary manually and that seemed to work.

**Comment by walkafwalka** [comment]
@TD-4242 Mind creating an issue over there? Another user has had installation issues. I am prioritizing working installation kinks out since those are arguably the most important.

**Pull request merged**
