### PR TITLE
Small fixes for helm3

### PR DESCRIPTION
**Pull request by anikin-aa**
Hi !

Small fixes for helm3, replace HELM_PLUGIN_PATH with HELM_PLUGIN_DIR.

`helm home` removed from helm3. This PR probably needs review.

I did not check compatibility with helm2

https://github.com/lrills/helm-unittest/issues/87

### CODE REVIEW

**Comment by davidkarlsen** [comment]
@lrills anything missing here or can it be merged?

**Comment by mmornati** [comment]
Just see that PR was open for this. Didn't understand how you are configuring the `HELM_PLUGIN_DIR` is this an env variable for Helm v3?
To allow a compatibility with Helm V2 why not simply change the line to retrieve the `helm home`. On my side (but I'm on mac) I replaced the `helm home` with `helm env` and then got the plugin fodlder from there.

```
: ${HELM_PLUGIN_PATH:="$(helm env | grep HELM_PLUGINS | awk -F '=' '{print $2}' | sed 's/\"//g')/helm-unittest"}
```

I think the piped command can be improved... but this worked on my MacOSx.
All is working just changing this line and keeping "safe" the rest of the script.

**Comment by anikin-aa** [comment]
@mmornati , hi
>  Didn't understand how you are configuring the HELM_PLUGIN_DIR is this an env variable for Helm v3?

Yep, this env variable for both helm v2/v3:

https://v2.helm.sh/docs/plugins/#building-plugins
https://helm.sh/docs/topics/plugins/

**Comment by lrills** [comment]
Close due to archiving repository.

Sorry for not presenting so long. I've been working on another project and don't have time to for helm-unittest.
Please consider other working forks like [quintush/helm-unittest](https://github.com/quintush/helm-unittest).

**Pull request closed without merging**
